(()=>{function R(e){return e.replace(/\{\{CURSOR\}\}/gi,"")}function a(e){let t=/\{\{CURSOR\}\}/i.exec(e);return e=R(e),{content:e,cursor:/^[ \t\r\n\f\v]*$/.test(e)?{kind:"none"}:{kind:"offset",value:t?.index??e.length,source:t?"marker":"defaultEnd"}}}function c(e,t,r=""){return{content:t+e.content+r,cursor:e.cursor.kind==="none"?e.cursor:{...e.cursor,value:t.length+e.cursor.value}}}var A=/\{(?=\{)|<(?=%)|%(?=>)/g,y=/([{<%])\uFDD0(?=[{%>])/g;function p(e){return e.replace(A,t=>t+"\uFDD0")}function l(e){return e.includes("\uFDD0")?e.replace(y,"$1"):e}function b(e,t){if(!e.includes("\uFDD0"))return{content:e,offsets:t};let r=s=>l(e.slice(0,s)).length;return{content:l(e),offsets:typeof t=="number"?r(t):t.map(r)}}function f(e){let{cursor:t}=e,r=b(e.content,t.kind==="offset"?t.value:0);return{content:r.content,cursor:t.kind==="offset"?{...t,value:r.offsets}:t}}function g(e){let t=/^---\r?\n(?:[\s\S]*?\r?\n)?---(?:\r?\n|$)/.exec(e);return{exists:!!t,contentStart:t?.[0].length??0}}var d=/^[^\S\r\n]*\r?\n/,k=/^\r?\n/,m=/^ {0,3}>/;function E(e,t){let r=e.replace(/\n$/,"").split(`
`).pop()??"",s=t.split(`
`,1)[0];return m.test(r)&&m.test(s)?`
`:""}function O(e){let t=g(e);return t.exists?t.contentStart:0}function T(e,t){let r=O(e);if(r===0)return 0;if(d.test(t))return r;let s=d.exec(e.slice(r));return s?r+s[0].length:r}function x(e,t,{separateBlockquotes:r=!1}={}){if(t.length===0)return{content:e,insertedStartOffset:null,insertedEndOffset:null};let s=T(e,t),n=e.slice(0,s),o=e.slice(s),u=n.length>0&&!n.endsWith(`
`)&&!k.test(t)?`
`:"",S=o.length>0&&!t.endsWith(`
`)?`
`:"",h=r?E(t,o):"",i=n.length+u.length,C=i+t.length;return{content:`${n}${u}${t}${S}${h}${o}`,insertedStartOffset:i,insertedEndOffset:C}}globalThis.knapperCapture=async e=>{try{let t=JSON.parse(e),r=t.template??"{{VALUE}}";if(r.replace(/\{\{(?:VALUE|CURSOR)\}\}/gi,"").includes("{{")||r.includes("<%"))throw Error("Unsupported QuickAdd template token");let s=r.replace(/\{\{VALUE\}\}/gi,()=>p(t.text)),n=f(a(s)),o=n;if(n.cursor.kind==="none")o={content:t.before,cursor:n.cursor};else if(t.position==="append"){let u=t.before.length&&!t.before.endsWith(`
`)?t.before+`
`:t.before;o=c(n,u)}else if(t.position==="top"){let u=x(t.before,n.content);o={content:u.content,cursor:n.cursor.kind==="offset"&&u.insertedStartOffset!==null?{...n.cursor,value:n.cursor.value+u.insertedStartOffset}:{kind:"none"}}}else throw Error("Unsupported capture position");return JSON.stringify({text:o.content,cursor:o.cursor,changed:o.content!==t.before})}catch(t){return JSON.stringify({error:String(t)})}};})();
