import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
const here = path.dirname(new URL(import.meta.url).pathname);
const upstream = path.resolve(here, '../vendor/dataview/src');
const originalIndex = fs.readFileSync(path.join(upstream, 'data-index/index.ts'), 'utf8');
// Extract unchanged upstream data structures, omitting Obsidian's live index.
const filters = originalIndex.slice(originalIndex.indexOf('export namespace PathFilters'), originalIndex.indexOf('/**\n * Caches in-use CSVs'));
const maps = originalIndex.slice(originalIndex.indexOf('export class IndexMap'));
fs.writeFileSync(path.join(here, 'upstream-index.ts'), '// Derived from ../vendor/dataview/src/data-index/index.ts (MIT). Generated by build.mjs.\n' + filters + maps);
const options = {
  absWorkingDir: path.resolve(here, '..'),
  bundle: true, format: 'iife', platform: 'browser', target: 'es2020', minify: true,
  mainFields: ['browser','module','main'],
  nodePaths: [path.join(here, 'node_modules'), upstream],
  alias: {'data-index/index': path.join(here, 'upstream-index.ts')},
  tsconfigRaw: {compilerOptions: {baseUrl: upstream, paths: {'*': ['*']}}},
  legalComments: 'inline', metafile: true,
};
const entries = ['engine', 'upstream-tests'];
const licenses = new Map();
for (const name of entries) {
  const result = await build({...options, entryPoints: [path.join(here, name + '.ts')], outfile: path.join(here, name + '.js')});
  fs.writeFileSync(path.join(here, name + '.meta.json'), JSON.stringify(result.metafile, null, 2) + '\n');
  // Include every transitive package notice in distributable binaries.
  for (const input of Object.keys(result.metafile.inputs)) {
    if (!input.includes('node_modules')) continue;
    let dir = path.dirname(path.resolve(input));
    while (dir.includes('node_modules')) {
      const pkg = path.join(dir, 'package.json');
      if (fs.existsSync(pkg)) {
        const info = JSON.parse(fs.readFileSync(pkg));
        if (!licenses.has(info.name + '@' + info.version)) {
          const files = fs.readdirSync(dir).filter(f => /^(license|licence|copying|notice)([.-]|$)/i.test(f));
          if (!files.length) throw Error('Missing license for ' + info.name);
          licenses.set(info.name + '@' + info.version, files.map(f => fs.readFileSync(path.join(dir,f), 'utf8')).join('\n'));
        }
        break;
      }
      dir = path.dirname(dir);
    }
  }
}
await build({...options, entryPoints: [path.join(here, 'engine.ts')], outfile: path.join(here,'native-engine.js'),
  plugins: [{name:'native-intl', setup(b) {b.onResolve({filter:/^\.\/polyfills$/}, () => ({path:path.join(here,'no-polyfills.ts')}));}}],
});
fs.writeFileSync(path.join(here, 'THIRD_PARTY_NOTICES.txt'),
  'Obsidian Dataview @ 5ad0994ff384cbb797de382e7edff2388141b73a\n' + fs.readFileSync(path.resolve(upstream, '../LICENSE.txt'), 'utf8') + '\n\n' +
  [...licenses].sort(([a],[b]) => a.localeCompare(b)).map(([name,license]) => name + '\n' + license).join('\n\n') +
  '\n\n' + fs.readFileSync(path.join(here, 'RUST_NOTICES.txt'), 'utf8'));
